kind: Service
apiVersion: v1
metadata:
  name: webapp-variation-service
  namespace: dev
spec:
  selector:
    app: webapp-variation
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000