pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '8.x'

  - task: Npm@1
    displayName: "npm install (production)"
    inputs:
      command: custom
      customCommand: npm install --only=production
      workingDir: src/

  - task: ArchiveFiles@2
    displayName: "Archive webapp src"
    inputs:
      rootFolderOrFile: src
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: "Copy File to: $(TargetFolder)"
    inputs:
      SourceFolder: "$(Build.ArtifactStagingDirectory)"
      Contents: "$(Build.BuildId).zip"
      TargetFolder: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/src'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: webapp-src"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/src'
      artifactName: 'src-drop'

  - task: CopyFiles@2
    displayName: "Copy webapp deployment template"
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/deploy/azure-webapp-arm/arm'
      targetFolder: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/deploy'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: deploy-src"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/deploy'
      artifactName: 'deploy-drop'
