variables:
  AzureConnection: 'Azure Subscription'
  ResourceGroup: 'webapp-variations'
  ResourceLocation: 'Central US'
  SiteName: 'wb-js-site-basic-arm'

pool:
  vmImage: 'vs2017-win2016'

trigger:
  branches:
    include: 
    - master
  paths:
    include:
    - azure-pipelines.yml
    - src/*
    - deploy/azure-webapp-arm/*

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '8.x'

  - task: Npm@1
    displayName: "npm install (production)"
    inputs:
      command: custom
      customCommand: install --only=production
      workingDir: src/

  - task: ArchiveFiles@2
    displayName: "Archive webapp src"
    inputs:
      rootFolderOrFile: src
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: "Copy File to: $(TargetFolder)"
    inputs:
      SourceFolder: "$(Build.ArtifactStagingDirectory)"
      Contents: "$(Build.BuildId).zip"
      TargetFolder: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/src'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: webapp-src"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/src'
      artifactName: 'src-drop'

  - task: AzureResourceGroupDeployment@2
    displayName: 'Create Or Update Resource Group'
    inputs:
      azureSubscription: '$(AzureConnection)'
      resourceGroupName: '$(ResourceGroup)'
      location: '$(ResourceLocation)'
      csmFile: '$(Build.SourcesDirectory)/deploy/azure-webapp-arm/arm/template.json'
      overrideParameters: '-site_name "$(SiteName)" -app_service_plan_name "$(SiteName)" -app_service_plan_sku {"name":"F1","tier":"Free","size":"F1","family":"F","capacity":0} -deployment_location "$(ResourceLocation)"'

  - task: AzureRmWebAppDeployment@3
    displayName: 'Deploy Azure App Service'
    inputs:
      azureSubscription: '$(AzureConnection)'
      WebAppName: '$(SiteName)'
      Package: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished/src/$(Build.BuildId).zip'
      GenerateWebConfig: true
      WebConfigParameters: '-Handler iisnode -NodeStartFile server.js -appType node'
      TakeAppOfflineFlag: true
      UseWebDeploy: true
      RemoveAdditionalFilesFlag: true
      RenameFilesFlag: true
