pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '8.x'

  - task: Npm@1
    displayName: "npm install"
    inputs:
      cwd: src
      arguments: "--only=production"

  - task: ArchiveFiles@2
    displayName: "Archive webapp src"
    inputs:
      rootFolderOrFile: src
      includeRootFolder: true

  - task: ArchiveFiles@2
    displayName: "Archive webapp deployment template"
    inputs:
      rootFolderOrFile: deploy/azure-webapp-arm/arm
      includeRootFolder: true

  - task: CopyFiles@2
    displayName: "Copy File to: $(TargetFolder)"
    inputs:
      SourceFolder: "$(Build.ArtifactStagingDirectory)"
      Contents: "$(Build.BuildId).zip"
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: webapp-src"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
