pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.x'

  - task: Npm@0
    displayName: "npm install"
    inputs:
      cwd: src
      arguments: "--force"

  - task: ArchiveFiles@2
    displayName: "Archive src"
    inputs:
      rootFolderOrFile: src
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: "Copy File to: $(TargetFolder)"
    inputs:
      SourceFolder: "$(Build.ArtifactStagingDirectory)"
      Contents: "$(Build.BuildId).zip"
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
