[environments]
  [environments.development]
    name = "wb-js-site"
    namespace = "dev"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
