---
- name: Destroy the demo environment
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - name: Delete the resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ azure_region }}"
        state: absent
        force: yes
        tags: "{{ default_tags }}"
