---
azure_region: southcentralus
resource_group_name: AnsibleWebAppDemo

virtual_network:
  name: VNET-ansible-webapp-demo
  cidr: 10.42.0.0/16

security_groups:
  - name: NSG-external
    rules:
      - name: AllowSSH
        protocol: Tcp
        destination_port_range: 22
        access: Deny
        priority: 100
        direction: Inbound
      - name: AllowWeb
        protocol: Tcp
        destination_port_range: 3000
        access: Allow
        priority: 200
        direction: Inbound

subnets:

  - name: SUB-external
    address_prefix_cidr: 10.42.50.0/24
    security_group_name: NSG-external

default_tags:
  environment: test
