# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "fedora29"

  config.vm.synced_folder "../../", "/home/vagrant/dev", type: "rsync",
    rsync__exclude: ".git/"

  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y upgrade
    sudo dnf install -y podman buildah
  SHELL
end
